CREATE TABLE IF NOT EXISTS accounts (
  `id` CHAR(36) NOT NULL DEFAULT (UUID()),
  `userId` CHAR(36) NOT NULL DEFAULT,
  `username` VARCHAR(255),
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `sites` VARCHAR(2048) NOT NULL,
  `notes` VARCHAR(255),
  `passwordChangedAt` TIMESTAMP NULL DEFAULT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deletedAt` TIMESTAMP NULL DEFAULT NULL,

  
  PRIMARY KEY (id),
  FOREIGN KEY (userId) REFERENCES users(`id`)
);